### ISSUE TITLE
auto_call_cna() function throws Error in wilcox.test

### ISSUE THREAD

**Issue by andynkili** [jmonlong/scCNAutils#4]
After running:
```
load('example-ge-coord-norm.RData')
cna.df = auto_cna_call(data, cells.df, prefix='example')

```
the following error was returned:
```
Creating metacells...
Normalizing and binning...
1138 expressed bins created.
Aneuploidy graph from metacells...
Scaling...
Smoothing...
Calling CNAs...
Error in wilcox.test.default(seg.mean, cont.mean) : 
  not enough 'y' observations
In addition: There were 50 or more warnings (use warnings() to see the first 50)

```

I thought some NAs could be the cause of this, so I checked `sum(is.na(cells.df))` and `sum(is.na(data))` but there seems to be none.
What should I do?

**Comment by jmonlong** [comment]
I couldn't replicate the bug but I have an idea on what could be causing it. 

This step is using segments with a predicted neutral copy number as baseline for the Wilcoxon test used to annotate the gains/losses. I had implemented it to look for neutral segments in the same chromosome but it can definitely happen that a chromosome doesn't have any. Now it will look also in other chromosomes for those baseline segments which should provide some control signal mean *cont.mean* for the test and fix this issue.

Could you try what's on the master branch now? If you still get an error, can you send me your data? For example the `example-ge-coord-norm.RData` and `cells.df`

**Comment by andynkili** [comment]
@jmonlong,

Since you have determined that error was coming from cells with lower depth, I am putting your answer to close the issue:
"The wilcoxon test can't find a "neutral" CN to test against, and it raises this error. First, thanks for noticing this. I will at the very least add proper warnings/error messages, and advice in those situations so that the user knows where to go from there. I think I can also design some kind of automated mode to adapt the parameters to the dataset.

Anyway, in your case, I'd have two recommendations

1) Filter the cells with low depth out from the beginning. This might be the best because there are clearly two modes if you look at the distribution of log(depth) (page 2 attached). I would filter out cells with less than 1000 reads for example (min_total_exp=1000 for auto_cna_signal). Also, the communities/tSNE look quite separated by depth (page 7 and 12). If you filter thos low-depth cells, you should get better tSNE, communities, and afterwards CNA calls.

2) Use bigger metacells and larger bins. To fight the dropout rate you could pool more cells than the default during the CNA calling, and also make larger bins. For example, I tried "metacell_size=30, bin_mean_exp=30" for auto_cna_call and got nicer calls (see page 15+). It's also sometimes easier to get a sense of the calls by picking some communities as baseline. Here I picked community 1 using "baseline_communities=1". Ideally, you'd guess which ones are the normal cells and use that. That's easier when you have multiple patients (normal cells cluster together) or some known CNA that you expect.

Even better, you could combine both 1) and 2)."


Again: thanks for you help,
Andy
